In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [35]:
###### Parameters

# fraction of sites occupied

# tolerance threshold
# - expand model to include neighbourhood size

L=4 # size of world, L
N=4 # number of each type of agents


###### Set up

#create an LxL lattice

#randomly populate the lattice

#np.random.choice([1,1,2,0],size=(L,L),replace=False)

num_sites = L*L
empty_sites = np.zeros(num_sites-2*N)
agent_list_1 = np.full(int(N),1)
agent_list_2 = np.full(int(N),2)

site_option_list = np.concatenate((empty_sites,agent_list_1,agent_list_2))

#site_option_list = np.append(site_option_list,agent_list_2)
print(site_option_list)

world = np.random.choice(site_option_list,size=(L,L),replace=False)
print(world)


###### Run

#loop over time:
    #loop over agents (sites that are non-zero):
        #count how many neighbours are of same type
        # check if that count is lower than threshold
        
    # loop over unsatisfied agents   
        #move unsatisfied agents

[0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 2. 2. 2. 2.]
[[1. 0. 0. 2.]
 [2. 2. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 1. 2.]]


In [9]:
cold_call(students)

[0. 1. 2. 1. 1. 0. 1.]


'Peyton'

In [2]:
def cold_call(students):
    global num_calls
    weights = (2**-num_calls)/np.sum(2**-num_calls)
    index_to_call = np.random.choice(range(len(students)),p=weights)
    num_calls[index_to_call] = num_calls[index_to_call] + 1
    print(num_calls)
    return students[index_to_call]

students = ['Francisco', 'Maanasee', 'Maria', 'Peyton', 'Matthew', 'Brielle', 'Brendon']
num_calls = np.zeros(len(students))

[0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 2. 2. 2. 2.]
[[2. 0. 0. 1.]
 [2. 0. 0. 0.]
 [0. 0. 2. 2.]
 [1. 1. 0. 1.]]
