In [3]:
#schelling model

#imports
import numpy as np
import matplotlib.pyplot as plt

# size of the world
L = 10

# half num_of agents
N = 25


### set up

num_sites = L*L
empty_sites = np.zeros(num_sites-2*N)
agent_list_1 = np.full(int(N),1)
agent_list_2 = np.full(int(N),2)

site_option_list = np.concatenate((empty_sites,agent_list_1,agent_list_2))

print(site_option_list)

world = np.random.choice(site_option_list,size=(L,L),replace=False)
print(world)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2.]
[[0. 0. 0. 0. 0. 1. 2. 0. 2. 0.]
 [1. 0. 0. 2. 1. 1. 2. 2. 0. 2.]
 [0. 2. 1. 2. 1. 0. 0. 2. 0. 0.]
 [0. 1. 2. 2. 0. 0. 0. 0. 0. 1.]
 [1. 0. 2. 0. 0. 0. 2. 0. 2. 0.]
 [0. 1. 0. 2. 0. 0. 2. 0. 2. 0.]
 [1. 2. 1. 1. 0. 0. 2. 1. 0. 1.]
 [1. 0. 1. 1. 1. 2. 1. 2. 0. 0.]
 [0. 1. 0. 0. 2. 1. 0. 0. 0. 2.]
 [1. 0. 2. 0. 2. 0. 1. 0. 1. 0.]]


In [ ]:
threshold = 4
# run

neighbors = [-1,0,1]
#check for number of unhappy individuals
for i in range(L):
    for j in range(L):
        count_like = 0
        if world(i,j) > 0:
            neighbors = [world(i-1,j-1),world(i-1,j),world(i-1,(j%L)+1),world(i,j-1),world(i,(j%L)+1),world((i%L)+1,j-1),world((i%L)+1,j),world((i%L)+1,(j%L)+1)] 
            for n in neighbors:
                if n == world(i,j):
                    count_like = count_like + 1
            if count_like<4:
                